<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <CustomConsole>..\MockSpectre\MockSpectre.csproj</CustomConsole>
    <StorageService>..\MockStorageService\MockStorageService.csproj</StorageService>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlannerService\PlannerService.csproj">
      <AdditionalProperties>
	StorageService=$(StorageService)
      </AdditionalProperties>
    </ProjectReference>
    <ProjectReference Include="..\EventPlanner-cli\EventPlanner-mocked.csproj">
    </ProjectReference>
    <ProjectReference Include="$(StorageService)" />
    <ProjectReference Include="$(CustomConsole)" />
  </ItemGroup>

</Project>